using MoneyShot.Services;
using Xunit;

namespace MoneyShot.Tests;

public class AutoUpdateServiceTests
{
    [Theory]
    [InlineData("v1.2.3", 1, 2, 3, 0)]
    [InlineData("v1.2.3-build.45.abc1234", 1, 2, 3, 45)]
    [InlineData("1.2.3", 1, 2, 3, 0)]
    [InlineData("v10.20.30", 10, 20, 30, 0)]
    [InlineData("v2.0.0-build.50", 2, 0, 0, 50)]
    [InlineData("Money Shot 1.2.3 release", 1, 2, 3, 0)]
    public void ParseVersion_ValidTags(string tag, int major, int minor, int patch, int build)
    {
        var version = AutoUpdateService.ParseVersion(tag);
        Assert.NotNull(version);
        Assert.Equal(major, version!.Major);
        Assert.Equal(minor, version.Minor);
        Assert.Equal(patch, version.Build);
        Assert.Equal(build, version.Revision);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("v1")]
    [InlineData("v1.2")]
    [InlineData("garbage")]
    [InlineData("no-numbers")]
    public void ParseVersion_InvalidTags_ReturnNull(string? tag)
    {
        var version = AutoUpdateService.ParseVersion(tag);
        Assert.Null(version);
    }

    [Theory]
    [InlineData("2.0.0.50", "2.0.0.45", 0)]
    [InlineData("2.0.0.45", "2.0.0.50", 0)]
    [InlineData("2.0.0", "2.0.0.50", 0)]
    [InlineData("2.0.1", "2.0.0", 1)]
    [InlineData("2.0.0", "2.0.1", -1)]
    [InlineData("2.1.0", "2.0.0", 1)]
    [InlineData("3.0.0", "2.9.9", 1)]
    [InlineData("2.0.0", "2.0.0", 0)]
    public void CompareSemVer_IgnoresBuildNumber(string aStr, string bStr, int expectedSign)
    {
        var a = Version.Parse(aStr);
        var b = Version.Parse(bStr);
        var result = AutoUpdateService.CompareSemVer(a, b);
        Assert.Equal(expectedSign, Math.Sign(result));
    }

    [Fact]
    public void SelectPreferredAsset_NullList_ReturnsNull()
    {
        Assert.Null(AutoUpdateService.SelectPreferredAsset(null));
    }

    [Fact]
    public void SelectPreferredAsset_EmptyList_ReturnsNull()
    {
        Assert.Null(AutoUpdateService.SelectPreferredAsset(Array.Empty<AutoUpdateService.ReleaseAsset>()));
    }

    [Fact]
    public void SelectPreferredAsset_PrefersExeOverZip()
    {
        var assets = new[]
        {
            new AutoUpdateService.ReleaseAsset { Name = "MoneyShot.zip", BrowserDownloadUrl = "https://example/zip" },
            new AutoUpdateService.ReleaseAsset { Name = "MoneyShot.exe", BrowserDownloadUrl = "https://example/exe" },
        };
        var picked = AutoUpdateService.SelectPreferredAsset(assets);
        Assert.NotNull(picked);
        Assert.EndsWith(".exe", picked!.Name);
    }

    [Fact]
    public void SelectPreferredAsset_FallsBackToZip()
    {
        var assets = new[]
        {
            new AutoUpdateService.ReleaseAsset { Name = "MoneyShot.msi", BrowserDownloadUrl = "https://example/msi" },
            new AutoUpdateService.ReleaseAsset { Name = "MoneyShot.zip", BrowserDownloadUrl = "https://example/zip" },
        };
        var picked = AutoUpdateService.SelectPreferredAsset(assets);
        Assert.NotNull(picked);
        Assert.EndsWith(".zip", picked!.Name);
    }

    [Fact]
    public void SelectPreferredAsset_OnlyMsi_ReturnsNull()
    {
        var assets = new[]
        {
            new AutoUpdateService.ReleaseAsset { Name = "MoneyShot.msi", BrowserDownloadUrl = "https://example/msi" },
        };
        Assert.Null(AutoUpdateService.SelectPreferredAsset(assets));
    }

    [Fact]
    public void ParseSha256Sums_FindsMatchingFile()
    {
        const string content = """
            abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890  MoneyShot.exe
            1111111111111111111111111111111111111111111111111111111111111111  MoneyShot.zip
            """;
        var hash = AutoUpdateService.ParseSha256Sums(content, "MoneyShot.exe");
        Assert.Equal("abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890", hash);
    }

    [Fact]
    public void ParseSha256Sums_IsCaseInsensitiveOnFilename()
    {
        const string content = "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890  MoneyShot.EXE";
        var hash = AutoUpdateService.ParseSha256Sums(content, "moneyshot.exe");
        Assert.NotNull(hash);
    }

    [Fact]
    public void ParseSha256Sums_HandlesBinaryModeStarPrefix()
    {
        const string content = "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890 *MoneyShot.exe";
        var hash = AutoUpdateService.ParseSha256Sums(content, "MoneyShot.exe");
        Assert.Equal("abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890", hash);
    }

    [Fact]
    public void ParseSha256Sums_SkipsCommentsAndBlanks()
    {
        const string content = """
            # Generated by CI

            abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890  MoneyShot.exe
            """;
        var hash = AutoUpdateService.ParseSha256Sums(content, "MoneyShot.exe");
        Assert.NotNull(hash);
    }

    [Fact]
    public void ParseSha256Sums_RejectsTruncatedHash()
    {
        const string content = "deadbeef  MoneyShot.exe";
        var hash = AutoUpdateService.ParseSha256Sums(content, "MoneyShot.exe");
        Assert.Null(hash);
    }

    [Fact]
    public void ParseSha256Sums_FileNotPresent_ReturnsNull()
    {
        const string content = "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890  Other.exe";
        Assert.Null(AutoUpdateService.ParseSha256Sums(content, "MoneyShot.exe"));
    }

    [Fact]
    public void ParseSha256Sums_EmptyContent_ReturnsNull()
    {
        Assert.Null(AutoUpdateService.ParseSha256Sums("", "MoneyShot.exe"));
        Assert.Null(AutoUpdateService.ParseSha256Sums("   ", "MoneyShot.exe"));
    }
}
